
package service.web.hotel2;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "HotelServiceImpl2Service", targetNamespace = "http://serviceWeb2/", wsdlLocation = "http://localhost:8080/hotelService2?wsdl")
public class HotelServiceImpl2Service
    extends Service
{

    private final static URL HOTELSERVICEIMPL2SERVICE_WSDL_LOCATION;
    private final static WebServiceException HOTELSERVICEIMPL2SERVICE_EXCEPTION;
    private final static QName HOTELSERVICEIMPL2SERVICE_QNAME = new QName("http://serviceWeb2/", "HotelServiceImpl2Service");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/hotelService2?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        HOTELSERVICEIMPL2SERVICE_WSDL_LOCATION = url;
        HOTELSERVICEIMPL2SERVICE_EXCEPTION = e;
    }

    public HotelServiceImpl2Service() {
        super(__getWsdlLocation(), HOTELSERVICEIMPL2SERVICE_QNAME);
    }

    public HotelServiceImpl2Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), HOTELSERVICEIMPL2SERVICE_QNAME, features);
    }

    public HotelServiceImpl2Service(URL wsdlLocation) {
        super(wsdlLocation, HOTELSERVICEIMPL2SERVICE_QNAME);
    }

    public HotelServiceImpl2Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, HOTELSERVICEIMPL2SERVICE_QNAME, features);
    }

    public HotelServiceImpl2Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HotelServiceImpl2Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IHotelService2
     */
    @WebEndpoint(name = "HotelServiceImpl2Port")
    public IHotelService2 getHotelServiceImpl2Port() {
        return super.getPort(new QName("http://serviceWeb2/", "HotelServiceImpl2Port"), IHotelService2.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IHotelService2
     */
    @WebEndpoint(name = "HotelServiceImpl2Port")
    public IHotelService2 getHotelServiceImpl2Port(WebServiceFeature... features) {
        return super.getPort(new QName("http://serviceWeb2/", "HotelServiceImpl2Port"), IHotelService2.class, features);
    }

    private static URL __getWsdlLocation() {
        if (HOTELSERVICEIMPL2SERVICE_EXCEPTION!= null) {
            throw HOTELSERVICEIMPL2SERVICE_EXCEPTION;
        }
        return HOTELSERVICEIMPL2SERVICE_WSDL_LOCATION;
    }

}
