
package service.web.hotel1;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "HotelNotFound", targetNamespace = "http://serviceWeb1/")
public class HotelNotFound_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private HotelNotFound faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public HotelNotFound_Exception(String message, HotelNotFound faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public HotelNotFound_Exception(String message, HotelNotFound faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: service.web.hotel1.HotelNotFound
     */
    public HotelNotFound getFaultInfo() {
        return faultInfo;
    }

}
